Fix an error when running `rake new_cop`
Follow up to https://github.com/rubocop/rubocop/pull/10109.

This commit fixes the following error.

```console
% bundle exec rake new_cop\[Department/CustomCop\]
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/Users/koic/src/github.com/rubocop/rubocop-performance/Rakefile:58:in
`new'
/Users/koic/src/github.com/rubocop/rubocop-performance/Rakefile:58:in
`block in <top (required)>'
/Users/koic/.rbenv/versions/3.1.0-dev/bin/bundle:23:in `load'
/Users/koic/.rbenv/versions/3.1.0-dev/bin/bundle:23:in `<main>'
Tasks: TOP => new_cop
(See full trace by running task with --trace)
```