Follow "Make it possible to set StyleGuideBaseURL per department"
Follow up https://github.com/rubocop-hq/rubocop/pull/7295.

This commit fixes the following error.

```console
% bundle exec rake
The `SafeMode` option will be removed in `RuboCop` 0.76. Please update
`rubocop-performance` to 1.15.0 or higher.
Files:          25
Modules:         3 (    3 undocumented)
Classes:        26 (    0 undocumented)
Constants:      50 (   45 undocumented)
Attributes:      0 (    0 undocumented)
Methods:        53 (   47 undocumented)
 28.03% documented
rake aborted!
ArgumentError: wrong number of arguments (given 3, expected 4)
tasks/cops_documentation.rake:154:in `new'
tasks/cops_documentation.rake:154:in `references'
tasks/cops_documentation.rake:24:in `cops_body'
tasks/cops_documentation.rake:197:in `print_cop_with_doc'
tasks/cops_documentation.rake:173:in `block in print_cops_of_department'
tasks/cops_documentation.rake:172:in `each'
tasks/cops_documentation.rake:172:in `print_cops_of_department'
tasks/cops_documentation.rake:268:in `block in main'
tasks/cops_documentation.rake:267:in `each'
tasks/cops_documentation.rake:267:in `main'
tasks/cops_documentation.rake:278:in `block in <top (required)>'
/Users/koic/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/koic/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => default => generate_cops_documentation
(See full trace by running task with --trace)
```